miestietis_main_homepage:
    path:     /
    defaults: { _controller: MiestietisMainBundle:Main:index }
ajax_problem:
    path:     /ajaxProblem
    defaults: { _controller: MiestietisMainBundle:Ajax:problem }
ajax_initiative:
    path: /ajaxInitiative
    defaults: { _controller: MiestietisMainBundle:Ajax:initiative }
ajax_upvote:
    path: /ajaxUpvote
    defaults: {_controller: MiestietisMainBundle:Ajax:upvote}
ajax_history:
    path:     /ajaxHistory
    defaults: { _controller: MiestietisMainBundle:Ajax:history }
ajax_comment:
    path:     /ajaxComment
    defaults: { _controller: MiestietisMainBundle:Ajax:comment }