miestietis_main_homepage:
    path:     /
    defaults: { _controller: MiestietisMainBundle:Main:index }
create:
    path:     /create
    defaults: { _controller: MiestietisMainBundle:User:create }

delete:
    path:     /delete
    defaults: { _controller: MiestietisMainBundle:User:delete }
ajax_problem:
    path:     /ajaxProblem
    defaults: { _controller: MiestietisMainBundle:Ajax:problem }
ajax_initiative:
    path: /ajaxInitiative
    defaults: { _controller: MiestietisMainBundle:Ajax:initiative }
ajax_upvote:
    path: /ajaxUpvote
    defaults: {_controller: MiestietisMainBundle:Ajax:upvote}
