services:
#    miestietis_main.example:
#        class: Miestietis\MainBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    my_user_provider.class: Miestietis\MainBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
    db_handler:
        class: Miestietis\MainBundle\Services\Database
        arguments: [ "@doctrine.orm.entity_manager" ]
    ob_formation:
        class: Miestietis\MainBundle\Services\Formation
        arguments: [ "@doctrine.orm.entity_manager" ]
    item_type:
        class: Miestietis\MainBundle\Services\Type
    image_handler:
        class: Miestietis\MainBundle\Services\Image
    counter:
        class: Miestietis\MainBundle\Services\Count